### ISSUE TITLE
Google Play Song Title Not Showing

### ISSUE THREAD

**Issue by Frink108** [PacoHobi/CurrentSong#5] opened 2015-06-12 02:11 UTC
Doesn't show the song title for Google Play, seems like they changed some of their code a while ago.  It used too.  The UNP plug-in updated the code to get the Google Play song id to "player-song-title", but it hasn't yet been updated to see if that works with Google Play now.

**Comment by PacoHobi** [comment] 2015-06-12 07:48
I noticed that issue yesterday and fixed it, but I'm also introducing a new feature and I want to make sure everything else is working before publishing the update. Expect an update in a few hours.

**Comment by PacoHobi** [comment] 2015-06-12 10:39
The issue is fixed with version v1.0.

Thank you for using CurrentSong, consider leaving a rating on the [OBS page](https://obsproject.com/forum/resources/currentsong.182/) and/or on [Mozilla Add-ons](https://addons.mozilla.org/en-US/firefox/addon/currentsong/). If you have any other issue or suggestion feel free to contact me :+1:

**Closed by PacoHobi** 2015-06-12 10:39 UTC
